export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const START_MOVIES_LIST = "START_MOVIES_LIST";
export const COMPLETED_MOVIES_LIST = "COMPLETED_MOVIES_LIST";

export const START_DETAILS_FETCHED = "START_DETAILS_FETCHED";
export const COMPLETED_DETAILS_FETCHED = "COMPLETED_DETAILS_FETCHED";
